#ifndef ENUM_TO_STRING_H
#define ENUM_TO_STRING_H

#include "ENUM_REGISTER.h"
#include "WR4T_WORKFLOW_tc.h"
#include "WRMC_WORKFLOW_tc.h"

namespace WRH
{

	REGISTER_ENUM_BEGIN(WR4T_EXCHANGE_TYPE_ENUM)
	{
		REGISTER_ENUM(WR4T_EXCHANGE_TYPE_PUT);
		REGISTER_ENUM(WR4T_EXCHANGE_TYPE_GET);
		REGISTER_ENUM(WR4T_EXCHANGE_TYPE_MOVE_TO_EXCHANGE);
		REGISTER_ENUM(WR4T_EXCHANGE_TYPE_MOVE_TO_RETRACT);
		REGISTER_ENUM(WR4T_EXCHANGE_TYPE_MOVE_TO_APPROACH);
		REGISTER_ENUM(WR4T_EXCHANGE_TYPE_MOVE_TO_DEFINE_LOW);
		REGISTER_ENUM(WR4T_EXCHANGE_TYPE_MOVE_TO_DEFINE_EXCHANGE);
		REGISTER_ENUM(WR4T_EXCHANGE_TYPE_MOVE_TO_DEFINE_HIGH);
		REGISTER_ENUM(WR4T_EXCHANGE_TYPE_SWAP_PUT_GET);
		REGISTER_ENUM(WR4T_EXCHANGE_TYPE_SWAP_PICKUP);
	}
	REGISTER_ENUM_END;

	REGISTER_ENUM_BEGIN(WR4T_ARM_STATION_ENUM)
	{
		REGISTER_ENUM(WR4T_ARM_STATION_A);
		REGISTER_ENUM(WR4T_ARM_STATION_B);
		REGISTER_ENUM(WR4T_ARM_STATION_C);
		REGISTER_ENUM(WR4T_ARM_STATION_D);
		REGISTER_ENUM(WR4T_ARM_STATION_E);
		REGISTER_ENUM(WR4T_ARM_STATION_F);
		REGISTER_ENUM(WR4T_ARM_STATION_G);
		REGISTER_ENUM(WR4T_ARM_STATION_H);
		REGISTER_ENUM(WR4T_ARM_STATION_I);
		REGISTER_ENUM(WR4T_ARM_STATION_J);
		REGISTER_ENUM(WR4T_ARM_STATION_K);
		REGISTER_ENUM(WR4T_ARM_STATION_L);
		REGISTER_ENUM(WR4T_ARM_STATION_M);
	}
	REGISTER_ENUM_END;

	REGISTER_ENUM_BEGIN(WRMC_SPEED_LEVEL_ENUM)
	{
		REGISTER_ENUM(WRMC_SPEED_LEVEL_HOME);
		REGISTER_ENUM(WRMC_SPEED_LEVEL_1);
		REGISTER_ENUM(WRMC_SPEED_LEVEL_2);
		REGISTER_ENUM(WRMC_SPEED_LEVEL_3);
		REGISTER_ENUM(WRMC_SPEED_LEVEL_4);
		REGISTER_ENUM(WRMC_SPEED_LEVEL_5);
		REGISTER_ENUM(WRMC_SPEED_LEVEL_6);
		REGISTER_ENUM(WRMC_SPEED_LEVEL_7);
		REGISTER_ENUM(WRMC_SPEED_LEVEL_8);
		REGISTER_ENUM(WRMC_SPEED_LEVEL_9);
	}
	REGISTER_ENUM_END;

	REGISTER_ENUM_BEGIN(WRMC_INFO_MODE_ENUM)
	{
		REGISTER_ENUM(WRMC_INFO_MODE_N);
		REGISTER_ENUM(WRMC_INFO_MODE_0);
		REGISTER_ENUM(WRMC_INFO_MODE_1);
		REGISTER_ENUM(WRMC_INFO_MODE_2);
		REGISTER_ENUM(WRMC_INFO_MODE_3);
	}
	REGISTER_ENUM_END;

}
#endif