#ifndef STATION_HEADER_H
#define STATION_HEADER_H

#include "ENUM_REGISTER.h"

typedef enum
{
	STATION_MIN = -1,
	STATION_TK_ILP,
	STATION_TK_RO,
	STATION_WH_PU,
	STATION_WH_LR,
	STATION_WH_UR,
	STATION_WH_DU,
	STATION_WS,
	STATION_MAX
}STATION_MOVE_WAFER_ENUM;


using namespace WRH;

REGISTER_ENUM_BEGIN(STATION_MOVE_WAFER_ENUM)
{
	REGISTER_ENUM(STATION_TK_ILP);
	REGISTER_ENUM(STATION_TK_RO);
	REGISTER_ENUM(STATION_WH_PU);
	REGISTER_ENUM(STATION_WH_LR);
	REGISTER_ENUM(STATION_WH_UR);
	REGISTER_ENUM(STATION_WH_DU);
	REGISTER_ENUM(STATION_WS);
}
REGISTER_ENUM_END;



#endif