#ifndef WRMC_106_H
#define WRMC_106_H


typedef enum
{
	WR_106_STATION_MIN,
	WR_106_STATION_WS,
	WR_106_STATION_PU,
	WR_106_STATION_LP,
	WR_106_STATION_TOP1,
	WR_106_STATION_TOP2,
	WR_106_STATION_DIS,
	WR_106_STATION_BOTTOM,
	WR_106_STATION_MAX
}WR_106_STATION_ENUM;


typedef struct 
{
	int T;
	int R;
	int Z;
	int stroke;
	int offset;
}WR_106_COODINATE_STRUCT;

typedef enum
{
	WR_106_EXCHANGE_MIN,
	WR_106_EXCHANGE_PUT_GET_DIRECT,
	WR_106_EXCHANGE_PICKUP,
	WR_106_EXCHANGE_PUT_GET_CUSTOM,
	WR_106_EXCHANGE_MAX
}WR_106_EXCHANGE_METHOD_ENUM;

typedef struct  
{
	WR_106_EXCHANGE_METHOD_ENUM exchange_method;
	WR_106_COODINATE_STRUCT coordinate;
}WR_106_EXCHANGE_PARAMETER_STRUCT;

typedef struct  
{
	WR_106_EXCHANGE_PARAMETER_STRUCT ws;
	WR_106_EXCHANGE_PARAMETER_STRUCT pu;
	WR_106_EXCHANGE_PARAMETER_STRUCT lp;
	WR_106_EXCHANGE_PARAMETER_STRUCT top1;
	WR_106_EXCHANGE_PARAMETER_STRUCT top2;
	WR_106_EXCHANGE_PARAMETER_STRUCT dis;
	WR_106_EXCHANGE_PARAMETER_STRUCT bottom;
}WR_106_STATION_EXCHANGE_PARAMETERS_STRUCT;


#endif